weapons:
  weapon_sharp_spear:
    damage: 5.0
    speed: -2.3500001430511475
  weapon_dark_lord_sword:
    damage: 5.0
    speed: -1.8000000715255737
  weapon_spider_fang:
    damage: 9.0
    speed: -2.6500000953674316
  weapon_sharp_curved_sword:
    damage: 5.0
    speed: -2.25
  weapon_dragons_doom:
    damage: 10.0
    speed: -2.700000047683716
  weapon_desert_wind:
    damage: 5.0
    speed: -2.200000047683716
  weapon_golden_horns_battleaxe:
    damage: 9.0
    speed: -2.6000001430511475
  weapon_old_blade:
    damage: 5.0
    speed: -2.4000000953674316
  weapon_infected_sharp_spear:
    damage: 6.0
    speed: -2.3500001430511475
  weapon_hand_of_malenia:
    damage: 7.0
    speed: -2.6500000953674316
  weapon_savage_sword:
    damage: 5.0
    speed: -2.450000047683716
  weapon_savage_dagger:
    damage: 4.0
    speed: -1.5000001192092896
  weapon_cursed_blade:
    damage: 10.0
    speed: -3.4200000762939453
  weapon_black_katana:
    damage: 5.0
    speed: -2.3000001907348633
  weapon_marika_hammer:
    damage: 12.0
    speed: -3.200000047683716
  weapon_thief_dagger:
    damage: 3.0
    speed: -1.0000001192092896
  weapon_fury_of_the_storm:
    damage: 10.0
    speed: -2.8500001430511475
  weapon_savage_hammer:
    damage: 7.0
    speed: -2.75
  weapon_wakizashi:
    damage: 4.0
    speed: -1.6000001430511475
  weapon_marai_executioner_sword:
    damage: 12.0
    speed: -3.1000001430511475
  weapon_infected_sharp_sword:
    damage: 7.0
    speed: -2.4000000953674316
  weapon_old_dagger:
    damage: 3.0
    speed: -1.2000001668930054
  weapon_golden_halberd:
    damage: 9.0
    speed: -2.750000238418579
  weapon_volcano_flame:
    damage: 11.0
    speed: -3.950000047683716
  weapon_crimson_reaper:
    damage: 9.0
    speed: -2.5500001907348633
  weapon_sharp_sword:
    damage: 6.0
    speed: -2.4000000953674316
  weapon_phantom_needle:
    damage: 4.0
    speed: -2.0
  weapon_fog_guard_sword:
    damage: 5.0
    speed: -2.450000047683716
  weapon_hero_claymore:
    damage: 11.0
    speed: -2.950000047683716
  weapon_old_broadsword:
    damage: 6.0
    speed: -2.450000047683716
  weapon_nagakiba:
    damage: 6.0
    speed: -2.4000000953674316
  weapon_spark_of_dawn_polearm:
    damage: 5.0
    speed: -2.3500001430511475
  weapon_kingslayer:
    damage: 8.0
    speed: -2.4200000762939453
  weapon_sunset_wings_claymore:
    damage: 10.0
    speed: -2.950000047683716
  weapon_wandering_wizard_sword:
    damage: 5.0
    speed: -2.25
  weapon_golden_execution_battleaxe:
    damage: 7.0
    speed: -2.6500000953674316
  weapon_forgotten_trace_spear:
    damage: 5.0
    speed: -2.3500001430511475
  weapon_rivers_of_blood:
    damage: 6.0
    speed: -2.3000001907348633
  weapon_dark_cover_sword:
    damage: 6.0
    speed: -2.4000000953674316
  weapon_infected_sharp_curved_sword:
    damage: 6.0
    speed: -2.25
  weapon_chess_board_knight_polearm:
    damage: 7.0
    speed: -2.6000001430511475
  weapon_eclipse_soldier_spear:
    damage: 6.0
    speed: -2.5500001907348633
  weapon_savage_spear:
    damage: 5.0
    speed: -2.3500001430511475
  weapon_fates_beacon:
    damage: 6.0
    speed: -2.4000000953674316
  weapon_dragonslayer_halberd:
    damage: 10.0
    speed: -2.8500001430511475
  weapon_hefty_club:
    damage: 5.0
    speed: -2.6000001430511475
